services:
  - type: web
    name: gou-app
    env: php
    buildCommand: "composer install"
    startCommand: "php artisan serve --host 0.0.0.0 --port 8000"
    plan: free
    branches:
      production:
        auto-deploy: true
    envVars:
      - key: APP_KEY
        value: your-app-key-here
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
